ServerEvents.recipes(e=>
{
    e.remove({id:'confluence:ankh_charm'});
    e.shapeless('confluence:ankh_charm',['confluence:the_plan','confluence:explorers_equipment','confluence:searchlight','confluence:nutrient_solution','confluence:detoxification_capsule']).stage('1_stage')                              
    e.remove({id:'confluence:hero_shield'});
    e.shapeless('confluence:hero_shield',['confluence:paladins_shield','confluence:flesh_knuckles']).stage('2_stage')
    e.remove({id:'confluence:terraspark_boots'});
    e.shapeless('confluence:terraspark_boots',['confluence:frostspark_boots','confluence:lava_waders']).stage('0_stage')
    e.remove({id:'irons_spellbooks:netherite_spell_book'});
    e.shapeless('irons_spellbooks:netherite_spell_book',['irons_spellbooks:magic_cloth','irons_spellbooks:magic_cloth','irons_spellbooks:magic_cloth','irons_spellbooks:magic_cloth','irons_spellbooks:blood_vial','irons_spellbooks:blood_vial',
    'irons_spellbooks:lightning_bottle','irons_spellbooks:ruined_book','minecraft:netherite_ingot']).stage('4_stage')
    e.remove({id:'irons_spellbooks:dragonskin_spell_book'});
    e.shapeless('irons_spellbooks:dragonskin_spell_book',['irons_spellbooks:dragonskin','irons_spellbooks:dragonskin','irons_spellbooks:dragonskin','irons_spellbooks:dragonskin','irons_spellbooks:dragonskin','irons_spellbooks:dragonskin',
    'minecraft:obsidian','irons_spellbooks:ruined_book','minecraft:obsidian']).stage('3_stage')
    e.remove({id:'mekanism:mekasuit_helmet'});
    e.shapeless('mekanism:mekasuit_helmet',['mekanism:hdpe_sheet','mekanism:hdpe_sheet','mekanism:hdpe_sheet','mekanism:hdpe_sheet','mekanism:ultimate_control_circuit','mekanism:pellet_polonium',
    'minecraft:netherite_helmet','mekanism:pellet_polonium','mekanism:basic_induction_cell']).stage('5_stage')
    e.remove({id:'mekanism:mekasuit_bodyarmor'});
    e.shapeless('mekanism:mekasuit_bodyarmor',['mekanism:hdpe_sheet','mekanism:hdpe_sheet','mekanism:hdpe_sheet','mekanism:hdpe_sheet','mekanism:ultimate_control_circuit','mekanism:pellet_polonium',
    'minecraft:netherite_chestplate','mekanism:pellet_polonium','mekanism:basic_induction_cell']).stage('6_stage')
    e.remove({id:'mekanism:mekasuit_pants'});
    e.shapeless('mekanism:mekasuit_pants',['mekanism:hdpe_sheet','mekanism:hdpe_sheet','mekanism:hdpe_sheet','mekanism:hdpe_sheet','mekanism:ultimate_control_circuit','mekanism:pellet_polonium',
    'minecraft:netherite_leggings','mekanism:pellet_polonium','mekanism:basic_induction_cell']).stage('7_stage')
    e.remove({id:'mekanism:mekasuit_boots'});
    e.shapeless('mekanism:mekasuit_boots',['mekanism:hdpe_sheet','mekanism:hdpe_sheet','mekanism:hdpe_sheet','mekanism:hdpe_sheet','mekanism:ultimate_control_circuit','mekanism:pellet_polonium',
    'minecraft:netherite_boots','mekanism:pellet_polonium','mekanism:basic_induction_cell']).stage('8_stage')
    e.remove({id:'mekanism:module_energy_unit'});
    e.shapeless('mekanism:module_energy_unit',['mekanism:hdpe_sheet','mekanism:hdpe_sheet','mekanism:hdpe_sheet','mekanism:alloy_infused','mekanism:alloy_infused','mekanism:alloy_infused',
    'mekanism:alloy_infused','mekanism:module_base','mekanism:basic_induction_cell']).stage('9_stage')
    e.remove({id:'cataclysm:smithing/ignitium_helmet'});
    e.shapeless('cataclysm:ignitium_helmet',['cataclysm:ignitium_upgrade_smithing_template','minecraft:netherite_helmet','cataclysm:ignitium_ingot']).stage('10_stage')
    e.remove({id:'cataclysm:smithing/ignitium_chestplate'});
    e.shapeless('cataclysm:ignitium_chestplate',['cataclysm:ignitium_upgrade_smithing_template','minecraft:netherite_chestplate','cataclysm:ignitium_ingot']).stage('11_stage')
    e.remove({id:'cataclysm:smithing/ignitium_leggings'});
    e.shapeless('cataclysm:ignitium_leggings',['cataclysm:ignitium_upgrade_smithing_template','minecraft:netherite_leggings','cataclysm:ignitium_ingot']).stage('12_stage')
    e.remove({id:'cataclysm:smithing/ignitium_boots'});
    e.shapeless('cataclysm:ignitium_boots',['cataclysm:ignitium_upgrade_smithing_template','minecraft:netherite_boots','cataclysm:ignitium_ingot']).stage('13_stage')
    e.remove({id:'cataclysm:smithing/cursium_helmet'});
    e.shapeless('cataclysm:cursium_helmet',['cataclysm:cursium_upgrade_smithing_template','minecraft:netherite_helmet','cataclysm:cursium_ingot']).stage('14_stage')
    e.remove({id:'cataclysm:smithing/cursium_chestplate'});
    e.shapeless('cataclysm:cursium_chestplate',['cataclysm:cursium_upgrade_smithing_template','minecraft:netherite_chestplate','cataclysm:cursium_ingot']).stage('15_stage')
    e.remove({id:'cataclysm:smithing/cursium_leggings'});
    e.shapeless('cataclysm:cursium_leggings',['cataclysm:cursium_upgrade_smithing_template','minecraft:netherite_leggings','cataclysm:cursium_ingot']).stage('16_stage')
    e.remove({id:'cataclysm:smithing/cursium_boots'});
    e.shapeless('cataclysm:cursium_boots',['cataclysm:cursium_upgrade_smithing_template','minecraft:netherite_boots','cataclysm:cursium_ingot']).stage('17_stage')
    e.remove({id:'cataclysm:the_incinerator'});
    e.shapeless('cataclysm:the_incinerator',['cataclysm:ignitium_ingot','minecraft:netherite_sword','cataclysm:ignitium_ingot','minecraft:blaze_rod','minecraft:blaze_rod','minecraft:blaze_rod','minecraft:blaze_rod']).stage('18_stage')
     e.remove({id:'cataclysm:weapon_infusion/gauntlet_of_maelstrom'});
    e.shapeless('cataclysm:gauntlet_of_maelstrom',['cataclysm:gauntlet_of_bulwark','cataclysm:sandstorm_in_a_bottle'])
    e.remove({id:'cataclysm:cursed_bow'});
    e.shapeless('cataclysm:cursed_bow',['cataclysm:cursium_ingot','minecraft:string','cataclysm:cursium_ingot','minecraft:string','minecraft:string','cataclysm:black_steel_ingot']).stage('19_stage')
     e.remove({id:'cataclysm:soul_render'});
    e.shapeless('cataclysm:soul_render',['cataclysm:cursium_ingot','cataclysm:cursium_ingot','cataclysm:cursium_ingot','cataclysm:black_steel_ingot','cataclysm:black_steel_ingot']).stage('20_stage')
     e.remove({id:'cataclysm:meat_shredder'});
    e.shapeless('cataclysm:meat_shredder',['cataclysm:witherite_ingot','cataclysm:witherite_ingot','minecraft:iron_block','minecraft:redstone','minecraft:redstone']).stage('21_stage')
    e.remove({id:'cataclysm:laser_gatling'});
    e.shapeless('cataclysm:laser_gatling',['cataclysm:witherite_ingot','cataclysm:witherite_ingot','minecraft:iron_ingot','minecraft:iron_ingot','minecraft:redstone','minecraft:iron_ingot','minecraft:redstone_block']).stage('24_stage')
     e.remove({id:'simplyswords:contained_remnant'});
     e.remove({id:'enigmaticlegacy:the_cube'});
     e.remove({id:'enigmaticlegacy:etherium_helmet'});
    e.shapeless('enigmaticlegacy:etherium_helmet',['enigmaticlegacy:etherium_ingot','enigmaticlegacy:etherium_ingot','enigmaticlegacy:etherium_ingot','enigmaticlegacy:etherium_ingot','enigmaticlegacy:etherium_ingot']).stage('26_stage')
    e.remove({id:'enigmaticlegacy:etherium_chestplate'});
    e.shapeless('enigmaticlegacy:etherium_chestplate',['enigmaticlegacy:etherium_ingot','enigmaticlegacy:etherium_ingot','enigmaticlegacy:etherium_ingot','enigmaticlegacy:etherium_ingot','enigmaticlegacy:etherium_ingot','enigmaticlegacy:etherium_ingot','enigmaticlegacy:etherium_ingot','enigmaticlegacy:etherium_ingot']).stage('27_stage')
  e.remove({id:'enigmaticlegacy:etherium_leggings'});
    e.shapeless('enigmaticlegacy:etherium_leggings',['enigmaticlegacy:etherium_ingot','enigmaticlegacy:etherium_ingot','enigmaticlegacy:etherium_ingot','enigmaticlegacy:etherium_ingot','enigmaticlegacy:etherium_ingot','enigmaticlegacy:etherium_ingot']).stage('28_stage')
     e.remove({id:'enigmaticlegacy:etherium_boots'});
    e.shapeless('enigmaticlegacy:etherium_boots',['enigmaticlegacy:etherium_ingot','enigmaticlegacy:etherium_ingot','enigmaticlegacy:etherium_ingot','enigmaticlegacy:etherium_ingot']).stage('29_stage')
       e.remove({id:'enigmaticlegacy:eldritch_pan'});
    e.shapeless('enigmaticlegacy:eldritch_pan',['enigmaticlegacy:evil_essence','enigmaticlegacy:evil_essence','enigmaticlegacy:void_stone','enigmaticlegacy:evil_ingot','enigmaticlegacy:evil_ingot','enigmaticlegacy:abyssal_heart','enigmaticlegacy:ender_rod','minecraft:ghast_tear','minecraft:ghast_tear']).stage('30_stage')
 e.remove({id:'enigmaticlegacy:infernal_shield'});
    e.shapeless('enigmaticlegacy:infernal_shield',['enigmaticlegacy:twisted_heart','minecraft:obsidian','minecraft:obsidian','minecraft:blaze_rod','minecraft:blaze_rod','minecraft:blaze_powder','minecraft:blaze_powder','minecraft:netherite_ingot','minecraft:shield']).stage('31_stage')
e.remove({id:'enigmaticaddons:etherium_core'});
    e.shapeless('enigmaticaddons:etherium_core',['enigmaticlegacy:ender_rod','enigmaticlegacy:ender_rod','enigmaticlegacy:ender_rod','enigmaticlegacy:ender_rod','enigmaticlegacy:etherium_boots','enigmaticlegacy:etherium_leggings','enigmaticlegacy:etherium_chestplate','enigmaticlegacy:etherium_helmet','enigmaticlegacy:golem_heart']).stage('41_stage')
  e.remove({id:'gobber2:gobber2_helmet_dragon'});
    e.shapeless('gobber2:gobber2_helmet_dragon',['minecraft:netherite_upgrade_smithing_template','gobber2:gobber2_helmet_end','gobber2:dragon_star']).stage('46_stage')
 e.remove({id:'gobber2:gobber2_chestplate_dragon'});
    e.shapeless('gobber2:gobber2_chestplate_dragon',['minecraft:netherite_upgrade_smithing_template','gobber2:gobber2_chestplate_end','gobber2:dragon_elytra']).stage('47_stage')
e.remove({id:'gobber2:gobber2_leggings_dragon'});
    e.shapeless('gobber2:gobber2_leggings_dragon',['minecraft:netherite_upgrade_smithing_template','gobber2:gobber2_leggings_end','gobber2:dragon_star']).stage('48_stage')
e.remove({id:'gobber2:gobber2_boots_dragon'});
    e.shapeless('gobber2:gobber2_boots_dragon',['minecraft:netherite_upgrade_smithing_template','gobber2:gobber2_boots_end','gobber2:dragon_star']).stage('49_stage')
    e.remove({id:'divinerpg:shaped/awakened_halite_helmet'});
    e.shapeless('divinerpg:awakened_halite_helmet',['divinerpg:divine_stone','divinerpg:divine_stone','divinerpg:divine_stone','divinerpg:divine_stone','divinerpg:arcanium','divinerpg:arcanium','divinerpg:corrupted_helmet','divinerpg:halite_helmet','divinerpg:halite_helmet']).stage('50_stage')
    e.remove({id:'divinerpg:shaped/awakened_halite_chestplate'});
    e.shapeless('divinerpg:awakened_halite_chestplate',['divinerpg:divine_stone','divinerpg:divine_stone','divinerpg:divine_stone','divinerpg:divine_stone','divinerpg:arcanium','divinerpg:arcanium','divinerpg:corrupted_chestplate','divinerpg:halite_chestplate','divinerpg:halite_chestplate']).stage('51_stage')
e.remove({id:'divinerpg:shaped/awakened_halite_leggings'});
    e.shapeless('divinerpg:awakened_halite_leggings',['divinerpg:divine_stone','divinerpg:divine_stone','divinerpg:divine_stone','divinerpg:divine_stone','divinerpg:arcanium','divinerpg:arcanium','divinerpg:corrupted_leggings','divinerpg:halite_leggings','divinerpg:halite_leggings']).stage('52_stage')
e.remove({id:'divinerpg:shaped/awakened_halite_boots'});
    e.shapeless('divinerpg:awakened_halite_boots',['divinerpg:divine_stone','divinerpg:divine_stone','divinerpg:divine_stone','divinerpg:divine_stone','divinerpg:arcanium','divinerpg:arcanium','divinerpg:corrupted_boots','divinerpg:halite_boots','divinerpg:halite_boots']).stage('53_stage')
e.remove({id:'alexscaves:extinction_spear'});
    e.shapeless('alexscaves:extinction_spear',['alexscaves:tectonic_shard','alexscaves:tectonic_shard','alexscaves:tectonic_shard','alexscaves:limestone_spear','alexscaves:amber_curiosity','alexscaves:amber_curiosity','alexscaves:heavy_bone']).stage('55_stage')
    e.remove({id:'legendary_monsters:the_great_frost'});
    e.shapeless('legendary_monsters:the_great_frost',['legendary_monsters:primal_ice_shard','legendary_monsters:primal_ice_shard','legendary_monsters:frozen_rune','minecraft:iron_sword']).stage('56_stage')
     e.remove({id:'legendary_monsters:wand_of_clouds'});
    e.shapeless('legendary_monsters:wand_of_clouds',['legendary_monsters:cloud_rod','legendary_monsters:air_rune','minecraft:iron_ingot']).stage('57_stage')
    e.remove({id:'legendary_monsters:axe_of_lightning'});
    e.shapeless('legendary_monsters:axe_of_lightning',['legendary_monsters:cloud_rod','legendary_monsters:air_rune','minecraft:iron_ingot']).stage('58_stage')
    e.remove({id:'legendary_monsters:monstrous_anchor'});
    e.shapeless('legendary_monsters:monstrous_anchor',['legendary_monsters:anchor_handle','minecraft:iron_ingot','minecraft:iron_ingot','minecraft:iron_block']).stage('59_stage')
    e.remove({id:'legendary_monsters:soul_great_sword'});
    e.shapeless('legendary_monsters:soul_great_sword',['legendary_monsters:corrupted_soul','minecraft:netherite_ingot','minecraft:diamond_sword']).stage('60_stage')
    e.remove({id:'soulsweapons:arkenplate'});
    e.shapeless('soulsweapons:arkenplate',['soulsweapons:arkenstone','minecraft:netherite_ingot','minecraft:iron_ingot','minecraft:netherite_ingot','minecraft:iron_ingot','minecraft:iron_ingot','soulsweapons:soul_ingot','soulsweapons:soul_ingot']).stage('62_stage')
     e.remove({id:'soulsweapons:withered_chest'});
    e.shapeless('soulsweapons:withered_chest',['soulsweapons:withered_demon_heart','minecraft:netherite_ingot','minecraft:nether_brick','minecraft:netherite_ingot','minecraft:nether_brick','minecraft:nether_brick','soulsweapons:crimson_ingot','soulsweapons:crimson_ingot']).stage('63_stage')
e.remove({id:'soulsweapons:chaos_orb'});
    e.shapeless('soulsweapons:chaos_orb',['soulsweapons:withered_demon_heart','soulsweapons:arkenstone','soulsweapons:essence_of_luminescence','soulsweapons:chaos_robes'])
    e.remove({id:'soulsweapons:moonlight_shortsword'});
    e.shapeless('soulsweapons:moonlight_shortsword',['soulsweapons:bluemoon_shortsword','minecraft:netherite_upgrade_smithing_template','#soulsweapons:lord_soul']).stage('64_stage')
    e.remove({id:'ice_and_fire_spellbooks:dragonmancer_oathbook'});
    e.shapeless('ice_and_fire_spellbooks:dragonmancers_oathbook',['#ice_and_fire_spellbooks:dragon_steel','#ice_and_fire_spellbooks:dragon_scales','#ice_and_fire_spellbooks:dragon_scales','irons_spellbooks:ruined_book','irons_spellbooks:magic_cloth']).stage('65_stage')
    e.remove({id:'soulsweapons:moonlight_greatsword'});
      e.remove({id:'soulsweapons:darkin_blade'});
e.remove({id:'soulsweapons:withered_wabbajack'});
    e.remove({id:'soulsweapons:dragonslayer_swordspear'});
    e.shapeless('soulsweapons:dragonslayer_swordspear',['#soulsweapons:lord_soul','minecraft:gold_ingot','minecraft:gold_ingot','minecraft:gold_ingot','minecraft:gold_ingot','minecraft:gold_ingot','minecraft:stick']).stage('69_stage')
    e.remove({id:'soulsweapons:rageblade'});
    e.shapeless('soulsweapons:rageblade',['#soulsweapons:lord_soul','minecraft:gold_ingot','minecraft:blaze_rod','minecraft:blaze_rod','minecraft:blaze_rod']).stage('70_stage')
    e.remove({id:'soulsweapons:nightfall'});
    e.remove({id:'soulsweapons:comet_spear'});
    e.shapeless('soulsweapons:comet_spear',['#soulsweapons:lord_soul','minecraft:gold_ingot','minecraft:gold_ingot','minecraft:gold_ingot','minecraft:gold_ingot','minecraft:gold_ingot','soulsweapons:moonstone','soulsweapons:moonstone']).stage('72_stage')
    e.remove({id:'soulsweapons:lich_bane'});
    e.shapeless('soulsweapons:lich_bane',['#soulsweapons:lord_soul','minecraft:diamond','minecraft:diamond','minecraft:copper_ingot','minecraft:blaze_rod']).stage('73_stage')
    e.remove({id:'soulsweapons:galeforce'});
    e.shapeless('soulsweapons:galeforce',['#soulsweapons:lord_soul','minecraft:string','minecraft:string','minecraft:string','soulsweapons:moonstone','soulsweapons:moonstone','soulsweapons:moonstone']).stage('74_stage')
    e.remove({id:'soulsweapons:soul_reaper'});
    e.remove({id:'soulsweapons:dawnbreaker'});
    e.remove({id:'soulsweapons:leviathan_axe'});
    e.shapeless('soulsweapons:leviathan_axe',['#soulsweapons:lord_soul','minecraft:stick','minecraft:stick','soulsweapons:verglas','soulsweapons:verglas']).stage('78_stage')
       e.remove({id:'soulsweapons:skofnung'});
    e.shapeless('soulsweapons:skofnung',['#soulsweapons:lord_soul','minecraft:iron_sword','minecraft:netherite_upgrade_smithing_template']).stage('79_stage')
    e.remove({id:'soulsweapons:mjolnir'});
    e.shapeless('soulsweapons:mjolnir',['#soulsweapons:lord_soul','minecraft:iron_block','minecraft:iron_block','minecraft:iron_block','minecraft:iron_block','minecraft:stick','soulsweapons:verglas']).stage('80_stage')
    e.remove({id:'soulsweapons:freyr_sword'});
    e.shapeless('soulsweapons:freyr_sword',['#soulsweapons:lord_soul','minecraft:iron_ingot','minecraft:iron_ingot','soulsweapons:moonstone','soulsweapons:verglas']).stage('81_stage')
    e.remove({id:'soulsweapons:crucible_sword'});
    e.shapeless('soulsweapons:crucible_sword',['#soulsweapons:lord_soul','minecraft:netherite_sword','minecraft:netherite_upgrade_smithing_template']).stage('82_stage')
    e.remove({id:'soulsweapons:darkin_scythe_pre'});
    e.shapeless('soulsweapons:darkin_scythe_pre',['#soulsweapons:lord_soul','minecraft:stick','soulsweapons:crimson_ingot','minecraft:stick','soulsweapons:crimson_ingot']).stage('83_stage')
    e.remove({id:'soulsweapons:draupnir_spear'});
    e.shapeless('soulsweapons:draupnir_spear',['#soulsweapons:lord_soul','minecraft:netherite_ingot','minecraft:blaze_rod']).stage('84_stage')
    e.remove({id:'soulsweapons:holy_moonlight_sword'});
    e.shapeless('soulsweapons:holy_moonlight_sword',['#soulsweapons:lord_soul','minecraft:netherite_upgrade_smithing_template','soulsweapons:sting']).stage('85_stage')
    e.remove({id:'soulsweapons:frostmourne'});
    e.shapeless('soulsweapons:frostmourne',['soulsweapons:lord_soul_night_peowler','soulsweapons:verglas','soulsweapons:verglas','soulsweapons:lord_soul_day_stalker','soulsweapons:soul_ingot','soulsweapons:soul_ingot','soulsweapons:soul_ingot']).stage('86_stage')
    e.remove({id:'soulsweapons:master_sword'});
    e.shapeless('soulsweapons:master_sword',['#soulsweapons:lord_soul','minecraft:netherite_upgrade_smithing_template','minecraft:diamond_sword']).stage('87_stage')
    e.remove({id:'soulsweapons:nights_edge_item'});
    e.shapeless('soulsweapons:nights_edge_item',['#soulsweapons:lord_soul','soulsweapons:moonstone','soulsweapons:moonstone','soulsweapons:moonstone','soulsweapons:soul_ingot','soulsweapons:soul_ingot','minecraft:stick']).stage('88_stage')
    e.remove({id:'soulsweapons:kraken_slayer_crossbow'});
    e.shapeless('soulsweapons:kraken_slayer_crossbow',['#soulsweapons:lord_soul','minecraft:gold_block','minecraft:crossbow','minecraft:iron_ingot','minecraft:iron_ingot','minecraft:iron_ingot','minecraft:iron_ingot']).stage('89_stage')
    e.remove({id:'soulsweapons:darkmoon_longbow'});
    e.shapeless('soulsweapons:darkmoon_longbow',['soulsweapons:essence_of_eventide','minecraft:gold_ingot','minecraft:stick','minecraft:gold_ingot','minecraft:string','minecraft:string','minecraft:string']).stage('90_stage')
    e.remove({id:'soulsweapons:dark_moon_greatsword'});
    e.shapeless('soulsweapons:dark_moon_greatsword',['#soulsweapons:lord_soul','soulsweapons:verglas','minecraft:stick','soulsweapons:verglas','soulsweapons:verglas','soulsweapons:verglas','soulsweapons:moonstone']).stage('91_stage')
    e.remove({id:'soulsweapons:glaive_of_hodir'});
    e.shapeless('soulsweapons:glaive_of_hodir',['#soulsweapons:lord_soul','minecraft:gold_ingot','minecraft:gold_ingot','soulsweapons:soul_ingot','soulsweapons:soul_ingot']).stage('92_stage')
    e.remove({id:'soulsweapons:excalibur'});
    e.shapeless('soulsweapons:excalibur',['#soulsweapons:lord_soul','minecraft:gold_ingot','minecraft:gold_ingot','soulsweapons:moonstone','minecraft:echo_shard','minecraft:echo_shard','minecraft:echo_shard']).stage('93_stage')
    e.remove({id:'soulsweapons:moonveil'});
    e.shapeless('soulsweapons:moonveil',['#soulsweapons:lord_soul','minecraft:iron_ingot','soulsweapons:moonstone','soulsweapons:moonstone','soulsweapons:moonstone']).stage('94_stage')
    e.remove({id:'mushroom_daydream:table/dragon_gobber'});
    e.remove({id:'mushroom_daydream:table/pure_horrorr'});
    e.remove({id:'mushroom_daydream:table/pure_horrorrrr'});
     e.remove({id:'mushroom_daydream:table/pure_horrorrr'});
    e.remove({id:'mushroom_daydream:table/pure_horror'});
    e.remove({id:'sakuratinker:materials/goozma/alloy'});
    e.remove({id:'traveloptics:wand_of_final_light'});
    e.shapeless('traveloptics:wand_of_final_light',['traveloptics:ancient_metal_weapon_parts','traveloptics:withered_excrucis','traveloptics:pocket_black_hole','minecraft:crying_obsidian']).stage('101_stage')
    e.remove({id:'traveloptics:trident_of_the_eternal_maelstrom'});
    e.shapeless('traveloptics:trident_of_the_eternal_maelstrom',['traveloptics:hullbreaker_steel','traveloptics:hullbreaker_steel','traveloptics:hullbreaker_steel','traveloptics:hullbreaker_steel','irons_spellbooks:weapon_parts','cataclysm:coral_bardiche']).stage('103_stage')
     e.remove({id:'sakuratinker:materials/etherium/etherium_melting'});
     e.remove({id:'traveloptics:smithing/forlorn_harbinger_hood'});
    e.shapeless('traveloptics:forlorn_harbinger_hood',['traveloptics:darkness_upgrade_smithing_template','traveloptics:darkness_cloth','irons_spellbooks:netherite_mage_helmet']).stage('112_stage')
    e.remove({id:'traveloptics:smithing/forlorn_harbinger_robe'});
    e.shapeless('traveloptics:forlorn_harbinger_robe',['traveloptics:darkness_upgrade_smithing_template','traveloptics:dark_gem_of_the_living_void','irons_spellbooks:netherite_mage_chestplate']).stage('113_stage')
    e.remove({id:'traveloptics:smithing/forlorn_harbinger_leggings'});
    e.shapeless('traveloptics:forlorn_harbinger_leggings',['traveloptics:darkness_upgrade_smithing_template','traveloptics:darkness_cloth','irons_spellbooks:netherite_mage_leggings']).stage('114_stage')
    e.remove({id:'traveloptics:smithing/forlorn_harbinger_boots'});
    e.shapeless('traveloptics:forlorn_harbinger_boots',['traveloptics:darkness_upgrade_smithing_template','traveloptics:darkness_cloth','irons_spellbooks:netherite_mage_boots']).stage('115_stage')
    e.remove({id:'traveloptics:smithing/tectonic_crest_armor_helmet'});
    e.shapeless('traveloptics:tectonic_crest_armor_helmet',['traveloptics:tectonic_upgrade_smithing_template','traveloptics:tectonic_ingot','traveloptics:primordial_crest_armor_helmet']).stage('116_stage')
    e.remove({id:'traveloptics:smithing/tectonic_crest_armor_chestplate'});
    e.shapeless('traveloptics:tectonic_crest_armor_chestplate',['traveloptics:tectonic_upgrade_smithing_template','traveloptics:tectonic_ingot','traveloptics:primordial_crest_armor_chestplate']).stage('117_stage')
    e.remove({id:'traveloptics:smithing/tectonic_crest_armor_leggings'});
    e.shapeless('traveloptics:tectonic_crest_armor_leggings',['traveloptics:tectonic_upgrade_smithing_template','traveloptics:tectonic_ingot','traveloptics:primordial_crest_armor_leggings']).stage('118_stage')
    e.remove({id:'traveloptics:smithing/tectonic_crest_armor_boots'});
    e.shapeless('traveloptics:tectonic_crest_armor_boots',['traveloptics:tectonic_upgrade_smithing_template','traveloptics:tectonic_ingot','traveloptics:primordial_crest_armor_boots']).stage('119_stage')
     e.remove({id:'traveloptics:smithing/abyssal_hide_armor_hat'});
    e.shapeless('traveloptics:abyssal_hide_armor_hat',['traveloptics:abyssal_upgrade_smithing_template','traveloptics:abyssal_spellweave_ingot','irons_spellbooks:netherite_mage_helmet']).stage('120_stage')
    e.remove({id:'traveloptics:smithing/abyssal_hide_armor_robe'});
    e.shapeless('traveloptics:abyssal_hide_armor_robe',['traveloptics:abyssal_upgrade_smithing_template','traveloptics:abyssal_spellweave_ingot','irons_spellbooks:netherite_mage_chestplate']).stage('121_stage')
    e.remove({id:'traveloptics:smithing/abyssal_hide_armor_leggings'});
    e.shapeless('traveloptics:abyssal_hide_armor_leggings',['traveloptics:abyssal_upgrade_smithing_template','traveloptics:abyssal_spellweave_ingot','irons_spellbooks:netherite_mage_leggings']).stage('122_stage')
    e.remove({id:'traveloptics:smithing/abyssal_hide_armor_boots'});
    e.shapeless('traveloptics:abyssal_hide_armor_boots',['traveloptics:abyssal_upgrade_smithing_template','traveloptics:abyssal_spellweave_ingot','irons_spellbooks:netherite_mage_boots']).stage('123_stage')
     e.remove({id:'traveloptics:smithing/cursed_wraithguard_crown'});
    e.shapeless('traveloptics:cursed_wraithguard_crown',['cataclysm:cursium_upgrade_smithing_template','cataclysm:cursium_ingot','irons_spellbooks:netherite_mage_helmet']).stage('124_stage')
    e.remove({id:'traveloptics:smithing/cursed_wraithguard_chestplate'});
    e.shapeless('traveloptics:cursed_wraithguard_chestplate',['cataclysm:cursium_upgrade_smithing_template','cataclysm:cursium_ingot','irons_spellbooks:netherite_mage_chestplate']).stage('125_stage')
    e.remove({id:'traveloptics:smithing/cursed_wraithguard_spectral_wrapping'});
    e.shapeless('traveloptics:cursed_wraithguard_spectral_wrapping',['cataclysm:cursium_upgrade_smithing_template','cataclysm:cursium_ingot','irons_spellbooks:netherite_mage_leggings']).stage('126_stage')
    e.remove({id:'traveloptics:smithing/cursed_wraithguard_boots'});
    e.shapeless('traveloptics:cursed_wraithguard_boots',['cataclysm:cursium_upgrade_smithing_template','cataclysm:cursium_ingot','irons_spellbooks:netherite_mage_boots']).stage('127_stage')
      e.remove({id:'traveloptics:smithing/mechanized_exoskeleton_helmet'});
    e.shapeless('traveloptics:mechanized_exoskeleton_helmet',['traveloptics:witherite_upgrade_smithing_template','cataclysm:witherite_ingot','irons_spellbooks:netherite_mage_helmet']).stage('128_stage')
    e.remove({id:'traveloptics:smithing/mechanized_exoskeleton_chestplate'});
    e.shapeless('traveloptics:mechanized_exoskeleton_chestplate',['traveloptics:witherite_upgrade_smithing_template','cataclysm:witherite_ingot','irons_spellbooks:netherite_mage_chestplate']).stage('129_stage')
    e.remove({id:'traveloptics:smithing/mechanized_exoskeleton_leggings'});
    e.shapeless('traveloptics:mechanized_exoskeleton_leggings',['traveloptics:witherite_upgrade_smithing_template','cataclysm:witherite_ingot','irons_spellbooks:netherite_mage_leggings']).stage('130_stage')
    e.remove({id:'traveloptics:smithing/mechanized_exoskeleton_boots'});
    e.shapeless('traveloptics:mechanized_exoskeleton_boots',['traveloptics:witherite_upgrade_smithing_template','cataclysm:witherite_ingot','irons_spellbooks:netherite_mage_boots']).stage('131_stage')
    e.shapeless('antiqueatlas:empty_antique_atlas',['minecraft:book','minecraft:compass'])
}
)
